import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

load_dotenv()

SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USERNAME = os.getenv("SMTP_USERNAME", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "")

def send_alert_email(subject: str, body_html: str):
    if not SMTP_USERNAME or not SMTP_PASSWORD or not ADMIN_EMAIL:
        print("⚠️ SMTP credentials not fully configured. Skipping email dispatch.")
        return False
        
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"EduMitra Alerts <{SMTP_USERNAME}>"
        msg["To"] = ADMIN_EMAIL

        part = MIMEText(body_html, "html")
        msg.attach(part)

        # Connect to server and send
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(SMTP_USERNAME, ADMIN_EMAIL, msg.as_string())
        
        print(f"✅ Alert email sent to {ADMIN_EMAIL}")
        return True
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False

def send_high_risk_alert(student_name: str, usn: str, avg_exam: float, avg_att: float, risk_details: dict):
    subject = f"[EduMitra Alert] High Risk Student Detected: {student_name} ({usn})"
    
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #FF4757;">⚠️ High Risk Student Alert</h2>
        <p>The EduMitra monitoring system has identified a student requiring immediate academic intervention.</p>
        <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
          <tr>
            <th style="text-align: left; border-bottom: 2px solid #eee; padding: 8px;">Metric</th>
            <th style="text-align: left; border-bottom: 2px solid #eee; padding: 8px;">Value</th>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Name</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">{student_name}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>USN</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">{usn}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Average Exam Score</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; color: {'#FF4757' if avg_exam < 50 else '#FFA502'};">{avg_exam}%</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Average Attendance</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; color: {'#FF4757' if avg_att < 50 else '#FFA502'};">{avg_att}%</td>
          </tr>
        </table>
        
        <h3>ML Risk Breakdown</h3>
        <p><strong>Overall Prediction:</strong> {risk_details.get('risk_level', 'Unknown')}</p>
        <ul>
        """
        
    if "probabilities" in risk_details:
        for k, v in risk_details["probabilities"].items():
            html += f"<li>{k}: {v}%</li>"
            
    html += """
        </ul>
        <p>Please log in to the EduMitra Admin Dashboard to review their full academic profile and initiate an intervention roadmap.</p>
        <br>
        <p style="font-size: 12px; color: #888;">This is an automated message generated by the EduMitra Monitoring System.</p>
      </body>
    </html>
    """
    
    return send_alert_email(subject, html)
